/* Configuration for erlang_nifs generated by Alire */
#ifndef ERLANG_NIFS_CONFIG_H
#define ERLANG_NIFS_CONFIG_H

#define CRATE_VERSION "0.1.0-dev"
#define CRATE_NAME "erlang_nifs"

#define ALIRE_HOST_OS "linux"

#define ALIRE_HOST_ARCH "x86_64"

#define ALIRE_HOST_DISTRO "distribution_unknown"

#define BUILD_PROFILE_RELEASE 1
#define BUILD_PROFILE_VALIDATION 2
#define BUILD_PROFILE_DEVELOPMENT 3

#define BUILD_PROFILE  3

#endif
